### ISSUE TITLE
"y" option is automatically placed in quotes after reopening HA editor

### ISSUE THREAD

**Issue by ildar170975** [nathan-gs/ha-map-card#10]
Open HA Editor & paste this code:
```
type: custom:map-card
x: 10
y: 10
```
Then save.
Works fine:

![изображение](https://github.com/nathan-gs/ha-map-card/assets/71872483/4d1bfe5c-a07a-4695-9d8d-e1ecf972b640)

Reopen the HA Editor.
Now the `y` option is shown in quotes:

![изображение](https://github.com/nathan-gs/ha-map-card/assets/71872483/06890334-c459-406d-9c2b-4d28bca15a66)

Guess a similar behaviour is demonstrated in Readme:

![изображение](https://github.com/nathan-gs/ha-map-card/assets/71872483/2ffae386-6139-4010-8da8-635f5e50396e)

0.4.0
HA 2024.3.1
Chrome 123.0.6312.59 (Win10x64)

**Comment by nathan-gs** [comment]
Unfortunately this is an issue with HA, not with this component.

**Comment by ildar170975** [comment]
OK, at least this behaviour is not harmful!
