### ISSUE TITLE
Lock map position option to prevent map scrolling

### ISSUE THREAD

**Issue by SeeThisIsMe** [nathan-gs/ha-map-card#100]
Hi,

I doubt I'm the only person who has this issue, but it would be a useful feature to have an option to lock the map position in place so that it prevents scrolling the map rather than scrolling the page. This is not an issue when using a computer, but for example when viewing the map on a phone and trying to scroll down the page of the HA dashboard its easy to end up scrolling the map rather than scrolling further down the dashboard page. 

Could this please be an option to add to the map?

Thanks!

**Comment by nathan-gs** [comment]
Likely it can be implemented by setting `dragging` on the `Map`: https://leafletjs.com/reference.html#map-dragging

**Comment by nathan-gs** [comment]
Checkout [v1.9.0](https://github.com/nathan-gs/ha-map-card/releases/tag/v1.9.0), you can now configure it as follows:

```yaml
type: custom:map-card
map_options:
  dragging: false
entities:
  - person.example
```

**Comment by SeeThisIsMe** [comment]
Hi @nathan-gs - after updating to v1.9.0 and adding the option it works perfectly :)

Many thanks!
