### ISSUE TITLE
[FR] Log a version info in a browser's console

### ISSUE THREAD

**Issue by ildar170975** [nathan-gs/ha-map-card#12]
Sorry if I named it in a wrong way - I mean these messages:

![изображение](https://github.com/nathan-gs/ha-map-card/assets/71872483/4ce68c71-21c8-4e8a-8507-bb04155840a3)

Custom cards usually post their version info.
It helps users to see which version was loaded (also to avoid loading an old cached version).

**Comment by nathan-gs** [comment]
Resolved in v0.5.0:
https://github.com/nathan-gs/ha-map-card/releases/tag/v0.5.0

**Comment by ildar170975** [comment]
@nathan-gs 
Thanks a lot for a quick patch!
But is it possible to make it a bit more vivid?
Currently it is displayed very "discrete" :

![изображение](https://github.com/nathan-gs/ha-map-card/assets/71872483/fb8209d6-ea1b-4b03-b6cc-82ed98929dfd)

All other custom cards are presented with vivid toxic colors, like shouting "yes, we a here!!!!!".

Smth like
```
console.info(
  `%c nathan-gs/ha-map-card: ${CARD_VERSION}`,
  'color: orange; font-weight: bold; background: black'
)
```

**Comment by nathan-gs** [comment]
Good idea, updated in v0.5.1

**Comment by ildar170975** [comment]
Much better!

![изображение](https://github.com/nathan-gs/ha-map-card/assets/71872483/60a6b926-695c-4469-b101-270bcb23c982)
