### ISSUE TITLE
[FR] Add a possibility to show states

### ISSUE THREAD

**Issue by ildar170975** [nathan-gs/ha-map-card#17]
The stock map card [allows to see a state](https://www.home-assistant.io/dashboards/map/#label_mode) instead of some icon/avatar:
![image](https://github.com/nathan-gs/ha-map-card/assets/71872483/9aef81f4-ab11-4b24-990e-08ed3ebb6904)

This allows to see values like:
![image](https://github.com/nathan-gs/ha-map-card/assets/71872483/02ab4e25-e79a-49cd-ac82-67fd5fa6eb12)

Would be great to have a similar option in this card as well.

**Comment by ildar170975** [comment]
An additional request: please provide ways to avoid this misaligned look:
![image](https://github.com/nathan-gs/ha-map-card/assets/71872483/fa14426b-29f8-4d58-ab03-e5665c4494d2)

**Comment by nathan-gs** [comment]
Fixed in [v0.8.0](https://github.com/nathan-gs/ha-map-card/releases/tag/v0.8.0)

Unfortunately the misaligned look cannot directly be fixed, because the ha-entity-marker is used to display (and this one has a fixed width & height + font size).

**Comment by ildar170975** [comment]
For a stack card I managed to fix alignment by
```
.marker:not(:has(.entity-picture)) {
      text-align: center;}
```
in an external js-file.

**Comment by nathan-gs** [comment]
Added the CSS in the latest release, however I don't think it's working due to how the Web Containers work.

**Comment by ildar170975** [comment]
Thanks a lot for the feature!

Unfortunately, do not see a state.
0.8.2
Here is a stock map card:
```
type: map
entities:
  - entity: sensor.narodmon_eee_radiation
    label_mode: state
```
![изображение](https://github.com/nathan-gs/ha-map-card/assets/71872483/ff88f8e6-7e1b-4066-a17b-a781255a825d)

Here is a ha-map-card:
```
type: custom:map-card
entities:
  - entity: sensor.narodmon_eee_radiation
```
![изображение](https://github.com/nathan-gs/ha-map-card/assets/71872483/116c0aca-e720-4dcc-9c08-81bec348b7a9)

But this does not show a marker at all:
```
type: custom:map-card
entities:
  - entity: sensor.narodmon_eee_radiation
     display: state
```
Zoomed out for security reasons:
![изображение](https://github.com/nathan-gs/ha-map-card/assets/71872483/f9a2c45a-173a-475b-bafb-5862fe12a38b)

F5, waiting - do not help.
Interesting that while I was editing in HA Editor - a state was shown! It happened once, could not reproduce.

**Comment by ildar170975** [comment]
Also please consider these cases:
- entity is unknown - may be then we should not see the marker
- entity is unavailable - some "wrong" label should be shown instead of long "unavailable"; this "label" should be clear for any languages; may be just "long dash" (w/o UoM)?

**Comment by nathan-gs** [comment]
> Also please consider these cases:
> 
>     * entity is unknown - may be then we should not see the marker
> 
>     * entity is unavailable - some "wrong" label should be shown instead of long "unavailable"; this "label" should be clear for any languages; may be just "long dash" (w/o UoM)?

We can only display entities with a latitude/longitude attributes. Unknown entities likely do not have these. Might be inspiration for a new feature though! 

P.s. I added more debug logging and also spotted a minor debug where the market kept getting recreated.

**Comment by nathan-gs** [comment]
> Thanks a lot for the feature!
> 
> Unfortunately, do not see a state. 0.8.2 Here is a stock map card:
> 
> ```
> type: map
> entities:
>   - entity: sensor.narodmon_eee_radiation
>     label_mode: state
> ```
> 
> ![изображение](https://private-user-images.githubusercontent.com/71872483/332106427-ff88f8e6-7e1b-4066-a17b-a781255a825d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMjE1NTksIm5iZiI6MTcxNjIyMTI1OSwicGF0aCI6Ii83MTg3MjQ4My8zMzIxMDY0MjctZmY4OGY4ZTYtN2UxYi00MDY2LWExN2ItYTc4MTI1NWE4MjVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDE2MDczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1YjBmYjQ0NDUxZmFjY2EyZDBkMjg4ZDM3OTc2NWI5YmU3NTgzNWJiOGRhNTg1ZjI0OWYwYzk5NmRkZTJjOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GfXgILK8-LhkNfgdJ_5HhVF4UB9rflX8HvnSJ9_bUmQ)
> 
> Here is a ha-map-card:
> 
> ```
> type: custom:map-card
> entities:
>   - entity: sensor.narodmon_eee_radiation
> ```
> 
> ![изображение](https://private-user-images.githubusercontent.com/71872483/332106620-116c0aca-e720-4dcc-9c08-81bec348b7a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMjE1NTksIm5iZiI6MTcxNjIyMTI1OSwicGF0aCI6Ii83MTg3MjQ4My8zMzIxMDY2MjAtMTE2YzBhY2EtZTcyMC00ZGNjLTljMDgtODFiZWMzNDhiN2E5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDE2MDczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5MzRiNDA4MzcyNTNjZmM1OGUzODhjOGQzNDUyZjI3Y2U1Zjk0ZWRiMmZlMWY3YmM0ZjVjZGQ1ZDcxNGJiZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.he-AQdN7aJVbmrzkT1R0fDjcB_dKA7fTS4Foy2H9_XU)
> 
> But this does not show a marker at all:
> 
> ```
> type: custom:map-card
> entities:
>   - entity: sensor.narodmon_eee_radiation
>      display: state
> ```
> 
> Zoomed out for security reasons: ![изображение](https://private-user-images.githubusercontent.com/71872483/332107065-f9a2c45a-173a-475b-bafb-5862fe12a38b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMjE1NTksIm5iZiI6MTcxNjIyMTI1OSwicGF0aCI6Ii83MTg3MjQ4My8zMzIxMDcwNjUtZjlhMmM0NWEtMTczYS00NzViLWJhZmItNTg2MmZlMTJhMzhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDE2MDczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMTAyMDlhODE1MzUzNjI1NWYxOWJjMzFkZWM0YThlYmI3ZGZhYTkxNDVlNzA5ZDg4MzZhYWFmYzU4MThkYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MyERhIwshSJTHtkalnpCnSrr4k-GqRitm8qgfFIrtkA)
> 
> F5, waiting - do not help. Interesting that while I was editing in HA Editor - a state was shown! It happened once, could not reproduce.

#32
