### ISSUE TITLE
Relicense to Apache 2.0

### ISSUE THREAD

**Issue by nathan-gs** [nathan-gs/ha-map-card#21]
@Manuel-Materazzo would you be OK if we relicensed to Apache 2.0 (instead of MIT) to make it easier to incorporate code from the Home Assistant frontend project?

**Comment by nathan-gs** [comment]
Also requested BrianEH approval in: https://community.home-assistant.io/t/map-card-map-change/98618/24

**Comment by Manuel-Materazzo** [comment]
Sure, it's perfectly fine by me

**Comment by nathan-gs** [comment]
Closing this one, most of the features of the native ha-map-card have been re-implemented from scratch.
