### ISSUE TITLE
Dark Mode auto switch

### ISSUE THREAD

**Issue by nathan-gs** [nathan-gs/ha-map-card#25]
_Originally posted by @alexreddy78 in https://github.com/nathan-gs/ha-map-card/issues/8#issuecomment-2119255742_
            
Auto switch to dark mode

**Comment by ildar170975** [comment]
Currently a stock map card has a [`theme_mode` option](https://www.home-assistant.io/dashboards/map/#theme_mode) with a similar purpose.
