### ISSUE TITLE
History: make dots vs lines configurable

### ISSUE THREAD

**Issue by nathan-gs** [nathan-gs/ha-map-card#26]
Any chance to get an option to turn off the history point "dots" and keep only the line in between? When moving in a small area, the dots fill the area rather rapidly.

_Originally posted by @Hiekkaharju in https://github.com/nathan-gs/ha-map-card/issues/8#issuecomment-2119268016_

**Comment by nathan-gs** [comment]
@Hiekkaharju fixed in [v0.7.1](https://github.com/nathan-gs/ha-map-card/releases/tag/v0.7.1)

**Comment by Hiekkaharju** [comment]
That was fast. Works fine. Thank you !!!

**Comment by ildar170975** [comment]
very useful, thank you!
