### ISSUE TITLE
History: do auto discovery of associated device_trackers and show history for these.

### ISSUE THREAD

**Issue by nathan-gs** [nathan-gs/ha-map-card#27]

**Comment by ildar170975** [comment]
Nathan, may I ask you to elaborate?
Is it about "gather all device_trackers & show them on a map"?
Some remarks:
1. Some integrations (like BLE) create tons of device_trackers; these entities may be not needed on a map.
2. A custom auto-entities card of Thomas Loven works fine with the `ha-map-card`; it creates a list of needed entities (could b persons, device_trackers, zones, sensors with coords - according to defined criteria) and then passes these entities (or dicts - including required per-entity options) into `ha-map-card`.
