### ISSUE TITLE
does not draw lines or dots when new coordinates arrive

### ISSUE THREAD

**Issue by Hiekkaharju** [nathan-gs/ha-map-card#28]
I'm not sure if this is a regression, some issue with my setup or was it like this from the beginning history feature.
When the card is drawn, history is also usually drawn according to history_draw nad history_show options. But then when new cordinates arrive, the marker moves but no line or dots appear.
tested version 0.7.1

**Comment by nathan-gs** [comment]
Normally the history should be redrawn when new items arrive, so a bug somewhere (or HA being slow...). Do note history is async through websockets.

**Comment by nathan-gs** [comment]
Just realized I convert `now` to the current timestamp... Obviously new items will not arrive.

**Comment by Hiekkaharju** [comment]
keeping that so, and making only start time specified mean that also future values shall be plotted might be an idea ?

**Comment by nathan-gs** [comment]
Added a special case for handling now. It's now working on my end.

**Comment by nathan-gs** [comment]
It should be solved in [v0.8.2](https://github.com/nathan-gs/ha-map-card/releases/tag/v0.8.2).

**Comment by Hiekkaharju** [comment]
working. Thanks.

**Comment by Elu43** [comment]
Hi
Thank you for your work. I have new dots being created but not all of them. It seems the update interval is bigger.
Here is with your card :

![image](https://github.com/nathan-gs/ha-map-card/assets/45129108/ffda663d-d80b-4533-8f85-491dd315027d)


And with HA classic card :

![image](https://github.com/nathan-gs/ha-map-card/assets/45129108/c8296e6d-1199-43d0-83f7-c10107000a6b)

**Comment by nathan-gs** [comment]
That's because the stock card uses all the available history from associated device_trackers, while this one only what you specify. I logged this as an improvement in #27
