### ISSUE TITLE
does not always draw trackers and history

### ISSUE THREAD

**Issue by Hiekkaharju** [nathan-gs/ha-map-card#29]
there is some issue with initial drawing, In some cases, at least right after dashboard edit, no indication of any trackers or history is drawn. On a browser e.g. f5 refresh fixes this.
Apparently -on android companion app- also just dashboard tab change from the view with the card to another and then back leaves the data undrawn.  I'm not aware of any refresh that would fix, exept restarting whole HA companion app.

**Comment by nathan-gs** [comment]
The history is loaded async, so it could be it's just slow.

**Comment by nathan-gs** [comment]
I added unsubscribe logic hopefully solving this.

**Comment by Hiekkaharju** [comment]
Sorry but this seems to still exist.
And now I checked also "from the view with the card to another and then back" with browser and that also fails (view= "tabs" on a dashboard.
When going to another dashboard and then returning works = from sidebar.

**Comment by nathan-gs** [comment]
Can you take a look at the Browser console to see if you see any error?

**Comment by Hiekkaharju** [comment]
I might have figured this out.
Adding
	   this.firstRenderWithMap = true;
to e.g. place where
            this.map.remove();
is done, seems to fix the issue.

**Comment by nathan-gs** [comment]
Very interesting @Hiekkaharju! I just noticed I might have the same issues in certain cases. Will try your work around!

**Comment by nathan-gs** [comment]
Can you test with [v0.9.0](https://github.com/nathan-gs/ha-map-card/releases/tag/v0.9.0)?

**Comment by Hiekkaharju** [comment]
Seems to work. Thanks again :)

OT + FYI: I see you added fallback coordinates. If I read the code correctly they will be used only if longitude/latitude is empty.
I've a device which returns -1,-1 as coordinates if it can't get a fix. I don't know if that's common.
I've already earlier made an automation which replaces those -1,-1 with fixed coordinates using see-service, so I do not need support for -1 fallback, but somone else might.

**Comment by nathan-gs** [comment]
Problem is -1,-1 however unlikely is a valid coordinate. Would be better to set it to null.

**Comment by nathan-gs** [comment]
It would not be hard to check for this. WDYT @Hiekkaharju?

**Comment by Hiekkaharju** [comment]
Based on your previous reply, if I were you, I would  leave it for now and if someone else later asks for it, take this as a +1
