### ISSUE TITLE
History Markers Not SHowing

### ISSUE THREAD

**Issue by totalitarian** [nathan-gs/ha-map-card#30]
Here is my working config for the regular map

<img width="349" alt="image" src="https://github.com/nathan-gs/ha-map-card/assets/2385696/ec3464f6-3bca-4efe-8f78-2268ec96fd2a">

```
type: map
entities:
  - entity: device_tracker.archies_iphone
default_zoom: 15
hours_to_show: 24
theme_mode: light
```

For some reason when I try to create via this addon it doesn't show the markers. Any idea why?

<img width="353" alt="image" src="https://github.com/nathan-gs/ha-map-card/assets/2385696/89a5c889-a0e9-4e84-a9dc-a0ea43e8ecb7">

```
type: custom:map-card
entities:
  - entity: device_tracker.archies_iphone
zoom: 15
card_size: 10
history_start: 24 hours ago

```

**Comment by Hiekkaharju** [comment]
You'll have to specify also history end time, e.g.     history_end: now

**Comment by nathan-gs** [comment]
The history options are per entity

**Comment by totalitarian** [comment]
> The history options are per entity

Perfect, thanks!
