### ISSUE TITLE
Can't zoom enough

### ISSUE THREAD

**Issue by vermut** [nathan-gs/ha-map-card#35]
Even native HA map allows more zoom. Ideally I'd like to have even more, as I'm tracking lawn mower and what to know precisely where it is on my lawn.

![image](https://github.com/nathan-gs/ha-map-card/assets/779376/c60b731b-7329-42e0-aef4-9776be44ca8b)

**Comment by nathan-gs** [comment]
That has something to do with the used tile layer, which you can customize. Each tile layer has other limits.

Easiest is to use the carto map HA uses.

**Comment by vermut** [comment]
As you see I'm on the defaults for both. Or I should **enable** Carto somehow for ha-map?

**Comment by nathan-gs** [comment]
For now maxZoom is 18 (as set by leaflet), unless you add a tilelayer with a higher maxZoom. 

Will add an option to override also the map's maxZoom, however you are still constrained with the max zoom level of the particular tilelayer.

**Comment by vermut** [comment]
Is there a way to use default tilelayer from builtin HA map? Because it allows more zoom as you can see on a screenshot

**Comment by nathan-gs** [comment]
This is how HA does it:
https://github.com/home-assistant/frontend/blob/dev/src/common/dom/setup-leaflet-map.ts#L40 

(as you can see, it uses maxZoom: 20 and a CARTOCDN map).

**Comment by nathan-gs** [comment]
> Is there a way to use default tilelayer from builtin HA map? Because it allows more zoom as you can see on a screenshot

Yes, it's possible, however using these require complying to the specific licenses, that's why using the standard openstreetmap option of leaflet is a safe default.

**Comment by nathan-gs** [comment]
```
tile_layer_options:
- maxZoom: 20
```

**Comment by nathan-gs** [comment]
@vermut which lawnmower are you using?

**Comment by vermut** [comment]
OpenMower. Why? :)

**Comment by nathan-gs** [comment]
Just curious :)
