### ISSUE TITLE
debug: true triggers error

### ISSUE THREAD

**Issue by nathan-gs** [nathan-gs/ha-map-card#50]
```
HaMapUtilities is not defined
```

See screenshot:

![image](https://github.com/nathan-gs/ha-map-card/assets/330943/78259f74-b0c2-487d-be68-936344048371)

@thybag

**Comment by thybag** [comment]
Let me pull and have a quick look. I must have missed an import somewhere.

**Comment by nathan-gs** [comment]
Fixed in latest release (added eslint)
