### ISSUE TITLE
HACS: Error:  <Plugin nathan-gs/ha-map-card> Repository structure for v1.0.0 is not compliant

### ISSUE THREAD

**Issue by nathan-gs** [nathan-gs/ha-map-card#52]
Since moving repo structure (and no longer using dist), the error: 
```Error:  <Plugin nathan-gs/ha-map-card> Repository structure for v1.0.0 is not compliant``` by hacs validation check is thrown.

**Comment by nathan-gs** [comment]
Hm, maybe it works if there is an ha-map-card.js file

**Comment by nathan-gs** [comment]
Fixed in v1.0.1

**Comment by sascha-hemi** [comment]
Same here.

**Comment by nathan-gs** [comment]
Very odd, nothing changed on this side since v1.0.1. The right file is in the release, the HACS validate action provides valid outputs: https://github.com/nathan-gs/ha-map-card/actions/runs/11203591562

**Comment by nathan-gs** [comment]
Hopefully fixed, by having a weekly cron doing the check.
