### ISSUE TITLE
Add "Discussions"

### ISSUE THREAD

**Issue by ildar170975** [nathan-gs/ha-map-card#6]
Not a bug/FR - just a kind request to add a "Discussions" section.
This is a too great card, it is surely need to be discussed)))

**Comment by ildar170975** [comment]
Sorry, just found your thread - https://community.home-assistant.io/t/map-card-a-slightly-improved-map-card/693088
So, it is up to you - either to use "Discussions" here or in the Community (myself prefer the Community).

**Comment by nathan-gs** [comment]
I will add a direct link to the discussion in the readme.

**Comment by nathan-gs** [comment]
Added a discussions & mentions section in the readme and changed the sidebar to https://community.home-assistant.io/t/map-card-a-slightly-improved-map-card/693088
