### ISSUE TITLE
Allow map to default to showing all Markers if no focus_entity or x/y is set.

### ISSUE THREAD

**Issue by thybag** [nathan-gs/ha-map-card#66]
I believe this should be doable by adding the markers to a `L.FeatureGroup`, then calling `map.fitBounds(markerGroup.getBounds());`

This way the default config will just cause the map to show everything tracked rather than focusing on the first entity.

**Comment by nathan-gs** [comment]
I like the idea! An addition to this would be to show the full tracks (as option)

**Comment by thybag** [comment]
As in include the visible location history within the bounds? 

That sounds like nice idea, although have to work out best way to get all the history data into a `L.FeatureGroup` as currently they are on separate layers (unsure if u can just put featureGroups in other featureGroups which would be ideal. ). I do like the idea of map rezooming as history data updates too, which would hopefully be pretty easy to add on top of the above.
