### ISSUE TITLE
Cannot zoom in like on a stock map card

### ISSUE THREAD

**Issue by ildar170975** [nathan-gs/ha-map-card#71]
Compare these cards - ha-map (left) & stock map (right):

![image](https://github.com/nathan-gs/ha-map-card/assets/71872483/ac9071eb-46e2-4d5c-964d-8b1a6959b766)

Same building; on the left card I cannot zoom in more.
Seems to be using same OpenStreetMap.
Are there any limitations for zooming?

**Comment by nathan-gs** [comment]
You can override the maxZoom of the tile layer:
https://leafletjs.com/reference.html#tilelayer

```
tile_layer_options:
  maxZoom: 25
```

**Comment by nathan-gs** [comment]
@ildar170975 would you mind adding this in the readme in a PR?

**Comment by ildar170975** [comment]
I would add details to readme as soon as understand it... 
See some strange behaviour:
1. Define maxZoom=20 - a map is not shown:
![image](https://github.com/nathan-gs/ha-map-card/assets/71872483/5e7ae87f-5a2f-4a01-99f4-947f7379dfe3)

2. Zoom out, zoom in (press "-", then "+") - a map is shown.
![image](https://github.com/nathan-gs/ha-map-card/assets/71872483/50c6ab11-fa6a-4913-8a89-566b25090334)

**Comment by nathan-gs** [comment]
Odd, can you look at the console and see if there are any issues loading?

**Comment by ildar170975** [comment]
Console:
![image](https://github.com/nathan-gs/ha-map-card/assets/71872483/8793551f-df0c-41f2-b003-97796cab93a9)

As for "Network" - not sure where to find:
![image](https://github.com/nathan-gs/ha-map-card/assets/71872483/4d148a30-9a77-4160-a45a-5e28f4d4bee1)

**Comment by nathan-gs** [comment]
It does mention BadRequest on the zoomed in 20 ones (first screenshot).

**Comment by ildar170975** [comment]
As for PR for readme:
in a stock map card a value is 20:
https://github.com/home-assistant/frontend/blob/76daa2bb7fa0676399d2ec40055deba0db23de9a/src/common/dom/setup-leaflet-map.ts#L50
So may be we should add as an example this "maxZoom: 20" case.

**Comment by ildar170975** [comment]
> It does mention BadRequest on the zoomed in 20 ones (first screenshot).

Interesting, I wonder are there any differences with a stock map card then.
No errors here:
![image](https://github.com/nathan-gs/ha-map-card/assets/71872483/89829553-969f-4ff8-9709-72940e3b89af)

**Comment by nathan-gs** [comment]
Added docs in [v1.5.1](https://github.com/nathan-gs/ha-map-card/releases/tag/v1.5.1)

**Comment by ildar170975** [comment]
@nathan-gs 
Thanks for a useful example in Readme!

Do you have any idea what could be a reason of a glitch described [here](https://github.com/nathan-gs/ha-map-card/issues/71#issuecomment-2189700671)?
