### ISSUE TITLE
[FR] History/displaying a path

### ISSUE THREAD

**Issue by ildar170975** [nathan-gs/ha-map-card#8]
A stock map card allows to show a path if `hours_to_show` option is defined:

![e413903372ef34b32411791f0f73d074708e3ea6](https://github.com/nathan-gs/ha-map-card/assets/71872483/ac436738-5a3c-456a-a884-9e7276c99fb7)

Also, it possible to see a time of a particular point in a tooltip:

![изображение](https://github.com/nathan-gs/ha-map-card/assets/71872483/dd2eea0a-26a0-4097-a68f-761adebf588e)

Would be great to have these features in this custom card.
Otherwise this card may only be used to see a current position only.

**Comment by aaamoeder** [comment]
Came here looking for this! that would be amazing ! thank you 😄

**Comment by alexreddy78** [comment]
Dear Nathan,

Any updates on this? Map is fantastic, very good detailed alternative to default one.

**Comment by nathan-gs** [comment]
Definitely doable, only need to find the time.

**Comment by dpl73** [comment]
The asthetic of the map displayed in your card is like night and day as compared to the stock HA map display. But I would also love to see the hours_to_show functionality.  Just wish I had the skill set to contribute.

**Comment by prigorus** [comment]
I would also kindly ask for adding the path/hours to show option. And a donate button. :)

**Comment by totalitarian** [comment]
Love this map. Hope to see this feature soon.

**Comment by nathan-gs** [comment]
I've been looking at it this evening, and also trying to understand how HA does it. It's not a 100% straightforward to get the history. Unfortunately I cannot directly extend the frontend (that would be great). 

The main code in HA is in this file:
https://github.com/home-assistant/frontend/blob/master/src/panels/lovelace/cards/hui-map-card.ts

**Comment by nathan-gs** [comment]
Looks like the only way to get the history, is using the callWs function, similar to:
https://github.com/home-assistant/frontend/blob/master/src/data/history.ts#L102

**Comment by nathan-gs** [comment]
From a config point of view I'm thinking of using a more flexible approach then `hours_to_show`. I was thinking per entity to have an option like: `startTime` and `endTime` which would accept a full datetime, but also a relative statement like `2 hours ago` & `now`.

WDYT?

**Comment by aaamoeder** [comment]
That sounds awesome 👍 thanks for taking the time to implement this 😉

**Comment by nathan-gs** [comment]
I started development and figured out to retrieve the history from HA, next up plotting this on a map. Getting closer!

**Comment by nathan-gs** [comment]
In v0.7.0 a basic version of the history is implemented, see the readme on how to use. It does have some missing functionality (eg. line opacity) compared to the stock HA Map.

**Comment by alexreddy78** [comment]
> In [v0.7.0](https://github.com/nathan-gs/ha-map-card/releases/tag/v0.7.0) a basic version of the history is implemented, see the readme on how to use. It does have some missing functionality (eg. line opacity) compared to the stock HA Map.

That's Fantastic! Did try! Thanks a lot!

PS If there is a chance to get auto switch to dark mode theme, as in standard Map?

**Comment by ildar170975** [comment]
@nathan-gs 
Thanks a lot for the feature.
Noticed that sometimes a track is not shown; may be shown after F5.

**Comment by Hiekkaharju** [comment]
Thank yoy very much for this ! Now I can get rid of a duplicate stock maps that existed only because of the history feature. 
Any chance to get an option to turn of the history point "dots" and keep only the line in between? When moving in a small area, the dots fill the area rather rapidly.

**Comment by ildar170975** [comment]
@alexreddy78 
> If there is a chance to get auto switch to dark mode theme, as in standard Map?

Suggest not to mix different features & register a separate FR.

**Comment by ildar170975** [comment]
@Hiekkaharju
> Any chance to get an option to turn off the history point "dots" and keep only the line in between? 

Suggest to register a separate FR.
