### ISSUE TITLE
Add an option to toggle which entities to show using helpers

### ISSUE THREAD

**Issue by franchiceddhu** [nathan-gs/ha-map-card#92]
Hello, first of all thanks for your exceptional map card addon. I find it extremely useful and well thought.

I was trying to fit several entities at once in a single map. Problem is, some entites are mostly grouped and quite far away from each other. I'd love to have a dynamic map that could show some entities at will, and focus on the ones in use.

I created a toggle helper called e.g. input_boolean.show_car and what I'd want is to have the map conditionally show this entity if the toggle is on (and hide it if off). Then I edited the ha-map-card entities section to look like this:

`entity: >-
      {{ 'device_tracker.car' if
      is_state('input_boolean.show_car', 'on') else '' }}`

The code is showing in blue, so it should be correct, yet I read "Error found in first run, check Console".

I'm not sure if I'm doing something wrong, but anyway such a option directly included as a feature would be extremely useful.

Thanks in advance.

**Comment by ildar170975** [comment]
> The code is showing in blue, so it should be correct

Templates are not supported. Color of code means nothing.

**Comment by franchiceddhu** [comment]
Thank you for you answer and your contributes. Any chances for templates to be supported? It would be such a useful feature.

**Comment by nathan-gs** [comment]
@franchiceddhu do you have examples of other `lovelace components` which have Template support? Because the template feature is typically not inside lovelace. 

A workaround is to create a new template sensor, which contains your template and just render that one.

**Comment by ildar170975** [comment]
1. Only a stock Markdown card has a jinja support for `content` option. Very few custom cards supports templates.
2. Another workaround - a map card may be placed inside a wrapper card supporting templates (config-template-card, card-templater, auto-entities, ...)

**Comment by franchiceddhu** [comment]
@nathan-gs 
Hi there, honestly apart from core Markdown I don't have any other examples. I was just fiddling with your component and I was surprised that it didn't have template support. However I'm still new to this world, so probably I was just asking for something that at the moment isn't supported at all.

A simple solution I applied was creating several maps with different entities, and then customizing their visibility. But this is only viable for 3 or 4 entities at once, not more.

**Comment by franchiceddhu** [comment]
@ildar170975 
Thanks for your suggestion, I didn't know about wrapper cards. Looks like they might be what I was searching for. I'll dig into this, thanks!

**Comment by nathan-gs** [comment]
@franchiceddhu if you get it working, feel free to make a PR for the readme with your insights.

**Comment by ildar170975** [comment]
@nathan-gs 
Do you mean that we can propose examples of using the `map-card` with other custom "wrapper" cards?
If yes - I may try providing these examples.
But I only see one use-case (same as described here) - "toggle which entities should be shown".
If you may suggest a different use-case - I will try to implement it.
(but not fast, things here are becoming worse every day, thanks to russian invasion)
